import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { ToastContainer } from 'react-toastify';

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

const poppins = localFont({
  src: [
    { path: "./fonts/Poppins-Thin.ttf", weight: "100" },
    { path: "./fonts/Poppins-Light.ttf", weight: "300" },
    { path: "./fonts/Poppins-Regular.ttf", weight: "400" },
    { path: "./fonts/Poppins-Medium.ttf", weight: "500" },
    { path: "./fonts/Poppins-SemiBold.ttf", weight: "600" },
    { path: "./fonts/Poppins-Bold.ttf", weight: "700" },
    { path: "./fonts/Poppins-ExtraBold.ttf", weight: "800" },
    { path: "./fonts/Poppins-Black.ttf", weight: "900" },
  ],
  variable: "--font-poppins",
});

export const metadata: Metadata = {
  title: "AGRIMART",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
    <head>
        <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;700&display=swap" rel="stylesheet"></link>
    </head>
      <body
          className={`${geistSans.variable} ${geistMono.variable} ${poppins.variable} antialiased`}
      >
      <ToastContainer
          theme="light"
      font-family= "Poppins, sans-serif"/>
        {children}
      </body>
    </html>
  );
}
